### PR TITLE
Update stretch_new_user_install.sh

### PR DESCRIPTION
**Pull request by vidhiJain**
To install new user workspace without sudo access

### CODE REVIEW

**Comment by hello-binit** [comment]
Hi @vidhiJain, thanks for the PR! Arduino-cli is required for the firmware updater to work, and interacting with some hardware will require sudo access if the user isn't part of the dialout, plugdev, and input groups.

**Comment by vidhiJain** [comment]
Is it possible for an account with sudo access to update the firmware and them to respective groups? Could we have separate scripts to install for a beginner user vs an admin user?

**Comment by hello-binit** [comment]
Is this to prevent "beginner" users from updating firmware? I think it should be possible. Would "beginner" users still need to be able to use Stretch Body or ROS? I'd need to confirm how important the groups are for Stretch Body to work.

**Comment by vidhiJain** [comment]
Yes, to prevent "beginner" users from updating firmware or doing something that breaks the functioning for others. Assuming a single "beginner" user session is active at a time, they need to be able to use Stretch Body or ROS. 
I had not found any issues in running regularly used Stretch Body and ROS commands. 
But today a "beginner" user tried `stretch_navigation` mapping.launch and the pose or map wouldn't update in their account. We verified that the issue does not occur when using default `hello-robot` user. We tried to grant sudo access to this user but it still failed. 
- is there something missing in `stretch_new_user_install.sh` that was present in default `hello-robot` user - say, the hardware access to get updated pose estimate?

**Comment by hello-binit** [comment]
Probably no, but I think I'd need more information to know for sure. When using mapping.launch, this beginner user is seeing the Rviz visualization of the robot not move even though the actual robot is moving?

**Comment by hello-binit** [comment]
Closing this as something that we aren't planning to support at the moment. Newly created users will need sudo access to function properly. Hopefully, we can change the required permissions in the future to support "beginner" users that do not have sudo access.

**Pull request closed without merging**
