### PR TITLE
Web interface install

### PR DESCRIPTION
**Pull request by hello-binit**
This PR installs the web interface located at https://github.com/hello-robot/stretch_teleop_interface into the Ament Workspace included with the Ubuntu 22.04 distribution. This PR was tested on two Stretchs.

### CODE REVIEW

**Comment by hello-binit** [comment]
@hello-vinitha is this branch still up-to-date?

**Comment by hello-vinitha** [comment]
> @hello-vinitha is this branch still up-to-date?

Yes, but I recently found some bugs that need to be resolved.

**Comment by binitshah** [comment]
With the install script or with the web interface?

**Comment by hello-vinitha** [comment]
The install script

**Pull request merged**
